In [1]:
import numpy as np
arr = np.arange(12)
print("Original array (1D):",arr)

Original array (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [2]:
arr_2d = arr.reshape(2,6)
print("\nReshape to 3X4:\n",arr_2d)


Reshape to 3X4:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [3]:
arr_3d = arr.reshape(2,3,2)
print("\nReshape to 2X3x2:\n",arr_3d)


Reshape to 2X3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [4]:
try :
    arr.reshape(3,4)
    print("\nReshape to(3,4) Successful")
    
    arr.reshape(2,5)
except ValueError as e:
    print("\nCannot reshape:",e)


Reshape to(3,4) Successful

Cannot reshape: cannot reshape array of size 12 into shape (2,5)


In [5]:
arr_2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
arr_auto = arr.reshape(2,-1)
print(" \nAUTO  SHAPED TO 2X6:\n",arr_auto)

 
AUTO  SHAPED TO 2X6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [8]:
arr_copy = arr.copy()
arr_copy.resize(5,3,refcheck = False)
print("\nResize to 5X3 (padded with zeos):\n",arr_copy)


Resize to 5X3 (padded with zeos):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  0  0]]


In [9]:
arr_3d_resize = arr.resize(2,3,2)
print("\nResizeArray: \n",arr_3d_resize)


ResizeArray: 
 None


In [10]:
print("\nResizeArray: \n",arr)


ResizeArray: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [11]:
import numpy as np
arr_2 = np.arange(12).reshape(3,4)
arr_2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr_ravel = arr_2.ravel()
print("\nFlattend array:",arr_ravel)


Flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
arr_ravel[0] = 1000
arr_ravel

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [15]:
arr_2

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [16]:
arr_2

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [17]:
arr_3 = np.arange(12).reshape(3,4)
arr_3
arr_flat = arr_3.flatten()
print("\nFlattend array:",arr_flat)


Flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
arr_3


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
arr_flat[0]=2000
arr_flat

array([2000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [20]:
arr_3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
arr = np.array([[1,2,3],[4,5,6]])
print("Original arry(2x3:\n",arr)
print("\nFlattend (row-major):",arr.flatten())
print("\nFlattend(column-major):",arr.flatten('F'))
print("\nRaveld:",arr.ravel('F'))

Original arry(2x3:
 [[1 2 3]
 [4 5 6]]

Flattend (row-major): [1 2 3 4 5 6]

Flattend(column-major): [1 4 2 5 3 6]

Raveld: [1 4 2 5 3 6]


In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array (2x3):\n", arr)
flat = arr.flatten()
print("\nFlattened (copy):", flat)
flat[0] = 100
print("Original after modifying flat:", arr[0,0])
raveled = arr.ravel()
print("\nRaveled (view):", raveled)
raveled[0] = 100
print("Original after modifying raveled:", arr[0,0])

Original array (2x3):
 [[1 2 3]
 [4 5 6]]

Flattened (copy): [1 2 3 4 5 6]
Original after modifying flat: 1

Raveled (view): [1 2 3 4 5 6]
Original after modifying raveled: 100


In [23]:
reshaped = arr.reshape(6)
print("\nReshaped to (6,):",reshaped)
reshaped[1]=200
print("Original after modifiying reshape:",arr[0,1])


Reshaped to (6,): [100   2   3   4   5   6]
Original after modifiying reshape: 200


In [24]:
arr_1d = np.arange(12)
print("\n1d array:",arr_1d)
print("Reshaped to 3x4 :\n",arr_1d.reshape(3,4))
print("Reshaped to 2x3x2\n",arr_1d.reshape(3,4))


1d array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
arr = np.array([[1,2,3],[4,5,6]])
print("Original array (2x3):",arr)

flat = arr.flatten()
print("\nFlattened(copy):",flat)
flat[0] = 100
print("Original after modifyinng flat:",arr[0,0])


Original array (2x3): [[1 2 3]
 [4 5 6]]

Flattened(copy): [1 2 3 4 5 6]
Original after modifyinng flat: 1


In [26]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[6:]

array([6, 7, 8, 9])

In [28]:
arr[-1:-5:-1]

array([9, 8, 7, 6])

In [29]:
arr[:5:-1]

array([9, 8, 7, 6])

In [30]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
arr = np.arange(10)
print("Array:",arr)
print("First element:",arr[0])
print("Last element:",arr[-1])
print("Slice from idex 2 to 5:",arr[2:5])
 

Array: [0 1 2 3 4 5 6 7 8 9]
First element: 0
Last element: 9
Slice from idex 2 to 5: [2 3 4]


In [32]:
print("Every other element:",arr[::2])

Every other element: [0 2 4 6 8]


In [33]:
print("Reversed array:",arr[::-1])

Reversed array: [9 8 7 6 5 4 3 2 1 0]


In [34]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D array:\n", arr_2d)


2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print("Element at row 1, column 2:", arr_2d[1, 2])
print("First row:", arr_2d[0, :])

Element at row 1, column 2: 6
First row: [1 2 3]


In [36]:
print("Last column:", arr_2d[:, -1])
print("Sub-matrix (first two rows, last two columns):\n", arr_2d[:2, 1:])

Last column: [3 6 9]
Sub-matrix (first two rows, last two columns):
 [[2 3]
 [5 6]]


In [37]:
print("\nElements greater than 5:", arr_2d[arr_2d > 5])


Elements greater than 5: [6 7 8 9]


In [38]:
print("Elements at positions [0,2] and [2,0]:", arr_2d[[0, 2], [2, 0]])

Elements at positions [0,2] and [2,0]: [3 7]


In [39]:
arr = np.array([1, 2, 3])
print("Array + scalar:", arr + 5)

Array + scalar: [6 7 8]


In [40]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
b=np.array([10, 20, 30])
b

array([10, 20, 30])

In [42]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])
print("\nMatrix + vector:\n", matrix + vector)


Matrix + vector:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [43]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30,50])
print("\nMatrix + vector:\n", matrix + vector)

ValueError: operands could not be broadcast together with shapes (3,3) (4,) 

In [ ]:
try:
    matrix = np.array([[1, 2, 3], [4, 5, 6]]) 
    vector = np.array([10, 20])                 
    print(matrix + vector)
except ValueError as e:
    print("\nBroadcasting error:", e)

In [ ]:

vector_reshaped = vector.reshape(2, 1)
print("\nMatrix + reshaped vector:\n", matrix + vector_reshaped)

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("From lists:\n", matrix)

In [ ]:
zeors_matrix = np.zeros((3,3))
print("\nZeros matrix:\n",zeors_matrix)

In [ ]:
ones_matrix = np.ones((2,4))
print("\nOnes matrix:\n",ones_matrix)

In [ ]:
identity_matrix = np.eye(3)
print("\nIdentity matrix:\n", identity_matrix)

In [ ]:
diagonal_matrix = np.diag([1, 2, 3, 4])
print("\nDiagonal matrix:\n", diagonal_matrix)

In [ ]:
random_matrix = np.random.random((3, 3))
print("\nRandom matrix:\n", random_matrix)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a)
print(b)
print("\nMatrix addition:\n", a + b)
print("\nMatrix multiplication:\n", np.matmul(a, b))
print("Dot product (same as matmul for 2D):\n", np.dot(a, b))
print("\nMatrix multiplication:\n", a @ b)  # Python 3.5+ operator    #prefered
print("\nElement-wise multiplication:\n", a * b)
print("\nMatrix transpose:\n", a.T)

In [ ]:
np.random.seed(2)
np.random.random(3)

In [ ]:
print("Random float [0,1):", np.random.random())
print("Random integer [0,10):", np.random.randint(10))

In [ ]:
print("\n3 random floats:", np.random.random(3))
print("2x3 random floats:\n", np.random.random((2, 3)))
print("5 random integers [1,100):", np.random.randint(1, 100, 5))

In [ ]:
print("\nNormal distribution (mean=0, std=1):", np.random.normal(size=5))

In [ ]:
print("Normal (mean=10, std=2):", np.random.normal(10, 2, 5))

In [ ]:
print("Uniform [0,1):", np.random.uniform(size=5))
print("Uniform [5,10):", np.random.uniform(5, 10, 5))

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("\nRandom choice:", np.random.choice(data, size=5))
print("Random choice with replacement:", np.random.choice(data, size=5, replace=True))
print("Shuffled array:", np.random.permutation(data))

In [ ]:
arr = np.array([1, 2, 3, 1, 2, 4, 5, 3, 2, 1])
print("Original array:", arr)
# Unique values
unique_values = np.unique(arr)
print("Unique values:", unique_values)

In [ ]:
unique_values, counts = np.unique(arr, return_counts=True)
print("\nValue counts:")
for val, cnt in zip(unique_values, counts):
    print(f"{val}: {cnt}")

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])
print("\n2D array:\n", arr_2d)

In [ ]:
print("\nUnique rows:\n", np.unique(arr_2d, axis=0))

In [ ]:
arr_3d = np.arange(24).reshape(2, 3, 4)
print("\n3D   )

In [ ]:
print("\nSwap axes 0 and 1 (3,2,4):\n", np.swapaxes(arr_3d, 0, 1))