In [22]:
import numpy as np
arr = np.arange(12)
print("Original array (1D):",arr)

Original array (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
arr_2d = arr.reshape(2,6)
print("\nReshape to 3X4:\n",arr_2d)


Reshape to 3X4:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [24]:
arr_3d = arr.reshape(2,3,2)
print("\nReshape to 2X3x2:\n",arr_3d)


Reshape to 2X3x2:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [25]:
try :
    arr.reshape(3,4)
    print("\nReshape to(3,4) Successful")
    
    arr.reshape(2,5)
except ValueError as e:
    print("\nCannot reshape:",e)


Reshape to(3,4) Successful

Cannot reshape: cannot reshape array of size 12 into shape (2,5)


In [26]:
arr_2d.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [28]:
arr_auto = arr.reshape(2,-1)
print(" \nAUTO  SHAPED TO 2X6:\n",arr_auto)

 
AUTO  SHAPED TO 2X6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [29]:
arr_copy = arr.copy()
arr_copy.resize(5,3,refcheck = False)
print("\nResize to 5X3 (padded with zeos):\n",arr_copy)


Resize to 5X3 (padded with zeos):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  0  0]]


In [30]:
arr_3d_resize = arr.resize(2,3,2)
print("\nResizeArray: \n",arr_3d_resize)


ResizeArray: 
 None


In [31]:
print("\nResizeArray: \n",arr)


ResizeArray: 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [32]:
import numpy as np
arr_2 = np.arange(12).reshape(3,4)
arr_2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
arr_ravel = arr_2.ravel()
print("\nFlattend array:",arr_ravel)


Flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [34]:
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
arr_ravel[0] = 1000
arr_ravel

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [36]:
arr_2

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [37]:
arr_2

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [38]:
arr_3 = np.arange(12).reshape(3,4)
arr_3
arr_flat = arr_3.flatten()
print("\nFlattend array:",arr_flat)


Flattend array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
arr_3


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
arr_flat[0]=2000
arr_flat

array([2000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [41]:
arr_3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr = np.array([[1,2,3],[4,5,6]])
print("Original arry(2x3:\n",arr)
print("\nFlattend (row-major):",arr.flatten())
print("\nFlattend(column-major):",arr.flatten('F'))
print("\nRaveld:",arr.ravel('F'))

Original arry(2x3:
 [[1 2 3]
 [4 5 6]]

Flattend (row-major): [1 2 3 4 5 6]

Flattend(column-major): [1 4 2 5 3 6]

Raveld: [1 4 2 5 3 6]


In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array (2x3):\n", arr)
flat = arr.flatten()
print("\nFlattened (copy):", flat)
flat[0] = 100
print("Original after modifying flat:", arr[0,0])
raveled = arr.ravel()
print("\nRaveled (view):", raveled)
raveled[0] = 100
print("Original after modifying raveled:", arr[0,0])

Original array (2x3):
 [[1 2 3]
 [4 5 6]]

Flattened (copy): [1 2 3 4 5 6]
Original after modifying flat: 1

Raveled (view): [1 2 3 4 5 6]
Original after modifying raveled: 100


In [45]:
reshaped = arr.reshape(6)
print("\nReshaped to (6,):",reshaped)
reshaped[1]=200
print("Original after modifiying reshape:",arr[0,1])


Reshaped to (6,): [1 2 3 4 5 6]
Original after modifiying reshape: 200


In [44]:
arr_1d = np.arange(12)
print("\n1d array:",arr_1d)
print("Reshaped to 3x4 :\n",arr_1d.reshape(3,4))
print("Reshaped to 2x3x2\n",arr_1d.reshape(3,4))


1d array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4 :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped to 2x3x2
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [43]:
arr = np.array([[1,2,3],[4,5,6]])
print("Original array (2x3):",arr)

flat = arr.flatten()
print("\nFlattened(copy):",flat)
flat[0] = 100
print("Original after modifyinng flat:",arr[0,0])


Original array (2x3): [[1 2 3]
 [4 5 6]]

Flattened(copy): [1 2 3 4 5 6]
Original after modifyinng flat: 1


In [48]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[6:]

array([6, 7, 8, 9])

In [50]:
arr[-1:-5:-1]

array([9, 8, 7, 6])

In [54]:
arr[:5:-1]

array([9, 8, 7, 6])

In [55]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr = np.arange(10)
print("Array:",arr)
print("First element:",arr[0])
pr int("Last element:",arr[-1])
print("Slice from idex 2 to 5:",arr[2:5])
 