In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np 
np.__version__

'2.5.3'

In [3]:
import numpy as np
print("NUMPY VERSION:-",np.__version__)

NUMPY VERSION:- 2.5.3


In [7]:
[ x*2 for x in [2,3,4]]

[4, 6, 8]

In [10]:
import time
python_list = list(range(1000000))
numpy_array = np.arange(1000000)

start = time.time()
result_list = [x*2 for x in python_list]
print("python list time :",time.time() -start, "seconds")

start = time.time()
result_array = numpy_array *2
print("NUMPY ARRAY TIME:", time.time()-start,"seconds")
print("python list size:",python_list.__sizeof__(),"bytes")
print("NUMPY ARRAY SIZE :",numpy_array.nbytes,"bytes")


python list time : 0.16407036781311035 seconds
NUMPY ARRAY TIME: 0.0072095394134521484 seconds
python list size: 8000040 bytes
NUMPY ARRAY SIZE : 8000000 bytes


In [14]:
import numpy as np 
li = [3,4,5]
print (type(li))
arr = np.array([1,2,3,4,5])
type(arr)


<class 'list'>


numpy.ndarray

In [21]:
arr = np.array([1,2,3,4,5])
print("1D array:",arr)

py_list = [1,2,3,4,5]
print("python list :",py_list)

arr_2d = np.array([[1,2,3] ,[3,4,5],[4,5,7]])
print("\n2D array:\n",arr_2d)

1D array: [1 2 3 4 5]
python list : [1, 2, 3, 4, 5]

2D array:
 [[1 2 3]
 [3 4 5]
 [4 5 7]]


In [23]:
list_1d = [1,2,3,4,5]
arr_1d = np.array(list_1d)
print("from 1D list:",arr_1d)


list_2d = [[1,2,3] ,[4,5,6]]
arr_2d = np.array(list_2d)
print("\nfrom 2D list:\n",arr_2d)



from 1D list: [1 2 3 4 5]

from 2D list:
 [[1 2 3]
 [4 5 6]]


In [24]:
a=np.array([1,2,])
a.dtype

dtype('int64')

In [30]:
int_array = np.array([1,2,3],dtype=np.int32)
float_array = np.array([1.0,2.0,3.0],dtype=np.float64)
bool_array =np.array([True , False,True],dtype = np.bool)
string_array = np.array(['apple','banana','cherry'],dtype=np.str_)

print("INTEGER ARRAY:",int_array,"DTYPE:",int_array.dtype)
print("FLOAT ARRAY:",float_array,"DTYPE:",float_array.dtype)
print("BOOLEAN ARRAY:",bool_array,"DTYPE:",bool_array.dtype)
print("STRING ARRAY:",string_array,"DTYPE:",string_array.dtype)

INTEGER ARRAY: [1 2 3] DTYPE: int32
FLOAT ARRAY: [1. 2. 3.] DTYPE: float64
BOOLEAN ARRAY: [ True False  True] DTYPE: bool
STRING ARRAY: ['apple' 'banana' 'cherry'] DTYPE: <U6


In [31]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [33]:
a=[1,2,3]
b=[4,5,6]
result=[]
for i in range(len(a)):
    for j in range (len(b)):
        if 1==j:
            result.append(a[i]+b[j])
print(result)

[6, 7, 8]


In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [36]:
print("\nELEMENT-WISE ADDITION:",a+b)
print("SUBSTARCTION:",a-b)
print("MULTIPLIVATION:",a*b)
print("DIVISION",b/a)
print("Exponentiation:",a**2)
print("MODULS:",b%a)



ELEMENT-WISE ADDITION: [5 7 9]
SUBSTARCTION: [-3 -3 -3]
MULTIPLIVATION: [ 4 10 18]
DIVISION [4.  2.5 2. ]
Exponentiation: [1 4 9]
MODULS: [0 1 0]


In [37]:
a=[1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [39]:
a=np.array([1,2,3])
print("\nSCALAR ADDITION:",a+10)
print("\nSCALAR MULTIPLICATION:",a*2)


SCALAR ADDITION: [11 12 13]

SCALAR MULTIPLICATION: [2 4 6]


In [5]:
import  numpy as np
arr=np.array([1,2,3,4,5])
print("\nSUM:",np.sum(arr))


SUM: 15


In [6]:
print("\nMEAN:",np.mean(arr))


MEAN: 3.0


In [7]:
print("STANDARD DEVIATION:",np.std(arr))

STANDARD DEVIATION: 1.4142135623730951


In [51]:
print("MINIMUM:",np.min(arr))

MINIMUM: 1


In [52]:
print("MAXIMUM:",np.max(arr))

MAXIMUM: 5


In [53]:
print("INDEX OF MAX:",np.argmax(arr))

INDEX OF MAX: 4


In [55]:
print("------------------------------------------------------------")

------------------------------------------------------------


In [56]:
print("\n ALL POSITIVE ?",np.all(arr>0))
print("\nGREATER THAN 4 :", np.any(arr>4))


 ALL POSITIVE ? True

GREATER THAN 4 : True


In [57]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])

print("ARRAY:\n",arr)

ARRAY:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
print("\nSHAPE:",arr.shape)


SHAPE: (3, 3)


In [59]:
print("SIZE:",arr.size)

SIZE: 9


In [63]:
print("Number of dimensions:",arr.ndim)
print("Data type ",arr.dtype)

Number of dimensions: 2
Data type  int64


In [64]:
print("ITEM SIZE (BYTES):",arr.itemsize)
print("TOTAL BYTES:",arr.nbytes)

ITEM SIZE (BYTES): 8
TOTAL BYTES: 72


In [65]:
print("------------------------------------------------------------")

------------------------------------------------------------


In [66]:
range_arr = np.arange(0,10,2)
print("\nRange array:",range_arr)


Range array: [0 2 4 6 8]


In [71]:
linspace=np.linspace(0,1,5)
print("\nLINERALY SPACE ARRAY:",linspace)


LINERALY SPACE ARRAY: [0.   0.25 0.5  0.75 1.  ]


In [72]:
arr = np.array([1,2,3])
print("ORIGINAL ARRAY:",arr)


ORIGINAL ARRAY: [1 2 3]


In [77]:
arr_append = np.append(arr,[4,5])
print("AFTER APPEND:",arr_append)

AFTER APPEND: [1 2 3 4 5]


In [78]:
arr_inserted = np.insert(arr,1,[10,20])
print("AFTER INSERT:",arr_inserted)


AFTER INSERT: [ 1 10 20  2  3]


In [79]:
arr_removed=np.delete(arr,[0,2])
print("AFTER DELETE :",arr_removed)

AFTER DELETE : [2]


In [82]:
unsorted = np.array([3,1,4,2,5])
unsorted_arr = np.sort(unsorted)
print("SORTED ARRAY:",unsorted_arr)

SORTED ARRAY: [1 2 3 4 5]


In [84]:
unsorted.sort()
print("In-PLACE SORTED:",unsorted)

In-PLACE SORTED: [1 2 3 4 5]


In [87]:
arr_2d = np.array([[3, 2, 9], [2, 5, 4]])
print("\n2D array before sort:\n", arr_2d)



2D array before sort:
 [[3 2 9]
 [2 5 4]]


In [86]:
print("Sorted along rows:\n", np.sort(arr_2d, axis=1))


Sorted along rows:
 [[2 3 9]
 [2 4 5]]


In [88]:
print("Sorted along columns:\n", np.sort(arr_2d, axis=0))

Sorted along columns:
 [[2 2 4]
 [3 5 9]]


In [2]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Array",arr)

Array [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
arr.shape

(5,)

In [11]:
arr.size

5

In [12]:
arr.ndim

1

In [13]:
len(arr)

5